// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCodqc_7kfKQXOCEBLbK1YqkeVpnoyVKwU',
    appId: '1:115906225321:web:6fba26d331a917641ef5b8',
    messagingSenderId: '115906225321',
    projectId: 'launchx-app-15',
    authDomain: 'launchx-app-15.firebaseapp.com',
    storageBucket: 'launchx-app-15.firebasestorage.app',
    measurementId: 'G-Y8PD04PWY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvmkup-CqqRdbaBEbl3vjr0oGZQop0FM',
    appId: '1:115906225321:android:6cca46a423f47b501ef5b8',
    messagingSenderId: '115906225321',
    projectId: 'launchx-app-15',
    storageBucket: 'launchx-app-15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQiPtGkAif8VQIq2_2hls1pjqZ3Oz9kHM',
    appId: '1:115906225321:ios:8f3936b434882aac1ef5b8',
    messagingSenderId: '115906225321',
    projectId: 'launchx-app-15',
    storageBucket: 'launchx-app-15.firebasestorage.app',
    iosBundleId: 'com.example.launchxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQiPtGkAif8VQIq2_2hls1pjqZ3Oz9kHM',
    appId: '1:115906225321:ios:8f3936b434882aac1ef5b8',
    messagingSenderId: '115906225321',
    projectId: 'launchx-app-15',
    storageBucket: 'launchx-app-15.firebasestorage.app',
    iosBundleId: 'com.example.launchxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCodqc_7kfKQXOCEBLbK1YqkeVpnoyVKwU',
    appId: '1:115906225321:web:e2dfbbca74e62b951ef5b8',
    messagingSenderId: '115906225321',
    projectId: 'launchx-app-15',
    authDomain: 'launchx-app-15.firebaseapp.com',
    storageBucket: 'launchx-app-15.firebasestorage.app',
    measurementId: 'G-3R3S244H5C',
  );
}
